import type { ReviewEmail } from '../src/shared.ts'

export const demoEmails: ReviewEmail[] = [
  {
    id: 'demo-train',
    threadId: 'thread-train',
    subject: 'Deine Verbindung am Montag',
    receivedAt: '2026-08-01T07:42:00Z',
    from: [{ name: 'Deutsche Bahn', email: 'reise@bahn.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-train@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'Deine Reise von Hamburg nach Berlin beginnt um 08:07 Uhr.',
    html: `<div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;color:#24231f"><p style="font-size:13px;letter-spacing:.08em;text-transform:uppercase;color:#716e64">Reiseinformation</p><h1 style="font-size:28px;line-height:1.2;margin:8px 0 24px">Hamburg → Berlin</h1><table role="presentation" style="width:100%;border-collapse:collapse;background:#f4f0e7"><tr><td style="padding:22px"><b>Mo, 3. August</b><br>ICE 705 · Wagen 8 · Platz 42</td><td style="padding:22px;text-align:right"><b>08:07</b><br>Hamburg Hbf</td></tr></table><p style="line-height:1.65">Deine Verbindung ist planmäßig. Bitte sei einige Minuten vor Abfahrt am Gleis.</p><a href="https://www.bahn.de" style="color:#9d4d32">Reise öffnen</a></div>`,
    text: 'Deine Reise von Hamburg nach Berlin beginnt am Montag um 08:07 Uhr.',
    mailboxNames: ['Inbox', 'Reisen'],
    hasAttachment: true,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [
      { blobId: 'demo-ticket', name: 'fahrkarte.pdf', type: 'application/pdf', size: 184_200 },
    ],
  },
  {
    id: 'demo-human',
    threadId: 'thread-human',
    subject: 'Re: Essen nächste Woche?',
    receivedAt: '2026-07-31T18:16:00Z',
    from: [{ name: 'Mara', email: 'mara@example.com' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-human@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'Donnerstag passt mir gut. Wollen wir wieder zu dem kleinen Italiener?',
    html: null,
    text: `Hey Alex,\n\nDonnerstag passt mir gut. Wollen wir wieder zu dem kleinen Italiener in der Schanze? 19 Uhr wäre perfekt.\n\nLiebe Grüße\nMara`,
    mailboxNames: ['Inbox'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-shop',
    threadId: 'thread-shop',
    subject: 'Deine Bestellung ist unterwegs · Sendungsnummer 00340434161094000000',
    receivedAt: '2026-07-31T11:03:00Z',
    from: [{ name: 'Nordlicht Markt', email: 'hallo@shop.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-shop@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview:
      'Bestellung NM-48291 wurde an DHL übergeben. Sendungsnummer 00340434161094000000, Zustellung voraussichtlich morgen.',
    html: `<div style="font-family:Helvetica,Arial,sans-serif;text-align:center;color:#24231f"><p style="font-size:12px;letter-spacing:.12em;text-transform:uppercase">Nordlicht Markt</p><h1 style="font-size:30px;margin:28px 0 12px">Es ist unterwegs.</h1><p style="font-size:17px;line-height:1.6">Dein Paket wurde an DHL übergeben<br>und kommt voraussichtlich morgen.</p><img src="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=720" alt="Paket im Versand" style="width:100%;max-width:560px;margin-top:24px"></div>`,
    text: 'Dein Paket wurde an DHL übergeben und kommt voraussichtlich morgen.',
    mailboxNames: ['Inbox', 'Bestellungen'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-dhl',
    threadId: 'thread-dhl',
    subject: 'DHL Sendungsnummer 00340434161094000000 ist auf dem Weg',
    receivedAt: '2026-07-31T12:16:00Z',
    from: [{ name: 'DHL', email: 'paket@dhl.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-dhl@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'Die Sendung 00340434161094000000 wurde elektronisch angekündigt.',
    html: null,
    text: 'Die Sendung wurde elektronisch angekündigt und soll morgen zugestellt werden.',
    mailboxNames: ['Inbox', 'Bestellungen'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-github-opened',
    threadId: 'thread-github-184',
    subject: '[beasty/inbox-walk] Pull request #184 opened',
    receivedAt: '2026-07-31T09:08:00Z',
    from: [{ name: 'GitHub', email: 'notifications@github.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-github-opened@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'Renovate opened PR #184 in beasty/inbox-walk for commit 7d2c1fa.',
    html: null,
    text: 'Renovate opened a dependency update pull request.',
    mailboxNames: ['Inbox'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-github-merged',
    threadId: 'thread-github-184',
    subject: '[beasty/inbox-walk] Pull request #184 merged',
    receivedAt: '2026-07-31T09:14:00Z',
    from: [{ name: 'GitHub', email: 'notifications@github.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-github-merged@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'PR #184 was merged into main as commit 7d2c1fa.',
    html: null,
    text: 'The pull request was merged.',
    mailboxNames: ['Inbox'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-railway-failed',
    threadId: 'thread-railway-7d2c1fa',
    subject: 'Railway deployment failed · beasty/inbox-walk · 7d2c1fa',
    receivedAt: '2026-07-31T09:20:00Z',
    from: [{ name: 'Railway', email: 'notifications@railway.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-railway-failed@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'The production deployment for beasty/inbox-walk commit 7d2c1fa failed to build.',
    html: null,
    text: 'The deployment failed during the image build.',
    mailboxNames: ['Inbox'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-railway-success',
    threadId: 'thread-railway-7d2c1fa',
    subject: 'Railway deployment successful · beasty/inbox-walk · 7d2c1fa',
    receivedAt: '2026-07-31T09:31:00Z',
    from: [{ name: 'Railway', email: 'notifications@railway.example' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-railway-success@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'The production deployment for commit 7d2c1fa is healthy.',
    html: null,
    text: 'The deployment completed and is healthy.',
    mailboxNames: ['Inbox'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-news',
    threadId: 'thread-news',
    subject: 'Samstagsbrief · Augustanfang',
    receivedAt: '2026-07-31T05:30:00Z',
    from: [{ name: 'Der Samstagsbrief', email: 'brief@journal.example' }],
    to: [{ name: '', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-news@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'Diese Woche: leise Orte, spätes Licht und drei gute Texte.',
    html: `<article style="font-family:Georgia,serif;max-width:620px;margin:0 auto;color:#27251f"><p style="font-family:Arial,sans-serif;font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#8b4e36">Ausgabe 164</p><h1 style="font-size:38px;font-weight:normal;line-height:1.12">Leise Orte, spätes Licht</h1><p style="font-size:19px;line-height:1.7">Ein Brief über kleine Ausflüge, lange Abende und Dinge, die im August ein wenig langsamer werden dürfen.</p><hr style="border:0;border-top:1px solid #d7d0c2;margin:32px 0"><h2 style="font-size:24px;font-weight:normal">Drei Lesestücke</h2><p style="font-size:17px;line-height:1.7">Eine Sammlung für das Wochenende – ungefähr zwanzig Minuten, eine Tasse Kaffee und kein weiterer Plan.</p></article>`,
    text: 'Ein Brief über kleine Ausflüge, lange Abende und Dinge, die im August langsamer werden dürfen.',
    mailboxNames: ['Newsletter'],
    hasAttachment: false,
    isNewsletter: true,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
  {
    id: 'demo-spam',
    threadId: 'thread-spam',
    subject: 'Falsch einsortierte Nachricht',
    receivedAt: '2026-07-30T12:00:00Z',
    from: [{ name: 'Bekannter Absender', email: 'kontakt@example.com' }],
    to: [{ name: 'Alex', email: 'alex@example.com' }],
    cc: [],
    replyTo: [],
    messageId: ['demo-spam@inbox-walk.local'],
    inReplyTo: [],
    references: [],
    preview: 'Diese Nachricht wurde fälschlich als Spam erkannt.',
    html: null,
    text: 'Diese Nachricht wurde fälschlich als Spam erkannt.',
    mailboxNames: ['Spam'],
    hasAttachment: false,
    isNewsletter: false,
    bodyTruncated: false,
    inlineResources: [],
    attachments: [],
  },
]
